### ISSUE TITLE
Ship AppStream metainfo file

### ISSUE THREAD

**Issue by Sesivany** [kgraefe/pidgin-birthday-reminder#3]
Hi,
I'd like to ask you if you could ship a small xml file that contains AppStream metadata. It's a distro-agnostic format for AppStore-like catalogs for Linux distributions: http://www.freedesktop.org/software/appstream/docs/sect-Quickstart-Addons.html
AppStream-based catalogs are currently included in all major Linux distributions: Fedora, Ubuntu, Debian, Arch,...
If the xml file is copied to %{datadir}/appdata/ (typically /usr/share/appdata) the plugin appears in the profile of the app (Pidgin) and is easily discoverable and installable for users.
I've create the file for you. See the attachment.
[pidgin-birthday-reminder.metainfo.xml.zip](https://github.com/kgraefe/pidgin-birthday-reminder/files/75464/pidgin-birthday-reminder.metainfo.xml.zip)

**Comment by kgraefe** [comment]
How is that used e.g. in Ubuntu? Isn't that part of the package building process?

Does the upstream Pidgin support that in any way? I could not find it in the source tarball.

**Comment by Sesivany** [comment]
Pidgin ships it upstream, I just checked. It's in /pidgin/data. It's just a different name: pidgin.appdata.xml because applications have a different file format than their extensions.

It can, of course, be added by packagers. What's necessary is that the file is in the package and copied to /usr/share/appdata (the distribution has a mechanism how to retrieve the metadata from packages and build a database of it so that users have info about apps and extensions before they're installed). But it's better to ship it upstream because 1. it can be used in all distributions, 2. upstream is in control of info that is shown to users.

The format is currently supported by GNOME Software which is the default GUI installer in Fedora, Ubuntu GNOME, and I believe Arch Linux and is present in other distributions (Debian,...). Ubuntu is currently switching to it from their Ubuntu Software Center, too, it will be in 16.04. I think KDE guys also already have some app store based on AppStream format.

**Comment by kgraefe** [comment]
Okay, thank you for your detailed explanation.

I will go for it, but it may take some time. I don't want to just take your metainfo.xml because I want it to be translatable and I do not agree with the license. (Not that I'm an expert in licenses, but most projects including Pidgin seem to go with CC0-1.0 and that is what I want to do as well.)

**Comment by kgraefe** [comment]
Can you please verify that the changes in [this branch](/kgraefe/pidgin-birthday-reminder/tree/appdata) do what you expect?

**Comment by Sesivany** [comment]
Looking at the build instructions, it seems to do what's expected. BTW I'm fine with CC0-1.0 license. In fact, I started using it as well because it's the least conflicting.
