### ISSUE TITLE
The plugin is not getting all birthdays on skypeweb

### ISSUE THREAD

**Issue by TomTheDragon** [kgraefe/pidgin-birthday-reminder#5]
It is really nice to see that there seems to be some life again in this project and i was quite happy, that the plugin extended the support even for skypeweb :)

But i just found out that the plugin dont seem to get all of the birthdays of my skypeweb buddies, only about 20% of them or so ..even if it can show the birthday date in pidgin (over the info page).

**Comment by kgraefe** [comment]
Can you get a screenshot of the info pages of a working and a non-working buddy? (You may obfuscate unrelated information.)

**Comment by TomTheDragon** [comment]
Okay, i made a screenshot of 4 info pages, the ones on the left were recognized and the ones on the right dont.
![bd_error_pidgin_01](https://cloud.githubusercontent.com/assets/7361323/12462334/02a07898-bfbe-11e5-9190-f52650f418a6.png)

[translation]
Vorname = First name
Nachname = Surname
Geburtstag = Birthday
Geschlecht = Sex
Stadt = Town

**Comment by kgraefe** [comment]
Okay, that is not what I expected. :-) There is an ancient bug with protocols that made the date format up to the client (ICQ afair), resulting in different formats for different buddies depending on _their_ locale. However, that might not be the case for Skype and is definitely not the cause in your case.

I'll have to build a debug version with additional debug output for you to run.

**Comment by kgraefe** [comment]
Okay, so I added some debug messages. Can you please try out the [Win32 build](http://kgraefe.github.io/pidgin-birthday-reminder/downloads/pidgin-birthday-reminder-1.8-debug1-win32.zip)?

Please open the debug window (Help -> Debug window) before scanning. You can easily trigger the scan for a specific buddy by opening its info window through the context menu.

**Comment by TomTheDragon** [comment]
I am guessing you need logs like this:
(i did change some little things like the buddy names)

---

(02:30:53) birthday-reminder: Scanning sven...
(02:30:53) birthday-reminder: Birthday not found. :~(

---

(02:33:51) birthday-reminder: Scanning fox...
(02:33:51) birthday-reminder: Birthday not found. :~(

---

(02:37:03) birthday-reminder: Scanning dragon...
(02:37:03) birthday-reminder: Birthday not found. :~(

---

**Comment by kgraefe** [comment]
Okay, let's try some [more output](https://github.com/kgraefe/pidgin-birthday-reminder/commit/84e365664a935c1de58494f3644d50e27d1fa4b2) ([Win32](http://kgraefe.github.io/pidgin-birthday-reminder/downloads/pidgin-birthday-reminder-1.8-debug-git84e3656-win32.zip)).

The lines starting with "birthday_reminder" are sufficient. ;-)

**Comment by TomTheDragon** [comment]
Okay here are some more logs:

---

(06:09:51) birthday-reminder: Scanning freak...
(06:09:51) birthday-reminder: needle: **Birthday**
(06:09:51) birthday-reminder: hay: **Vorname**
(06:09:51) birthday-reminder: hay: **Geburtstag**
(06:09:51) birthday-reminder: hay: **Geschlecht**
(06:09:51) birthday-reminder: hay: **Language**
(06:09:51) birthday-reminder: hay: **Info**
(06:09:51) birthday-reminder: Birthday not found. :~(

---

(06:11:34) birthday-reminder: Scanning harren...
(06:11:34) birthday-reminder: needle: **Birthday**
(06:11:34) birthday-reminder: hay: **Vorname**
(06:11:34) birthday-reminder: hay: **Geburtstag**
(06:11:34) birthday-reminder: hay: **Geschlecht**
(06:11:34) birthday-reminder: hay: **Language**
(06:11:34) birthday-reminder: hay: **Land**
(06:11:34) birthday-reminder: hay: **Province**
(06:11:34) birthday-reminder: hay: **Homepage**
(06:11:34) birthday-reminder: hay: **Info**
(06:11:34) birthday-reminder: Birthday not found. :~(

---

(06:13:07) birthday-reminder: Scanning samson...
(06:13:07) birthday-reminder: needle: **Birthday**
(06:13:07) birthday-reminder: hay: **Vorname**
(06:13:07) birthday-reminder: hay: **Geburtstag**
(06:13:07) birthday-reminder: hay: **Language**
(06:13:07) birthday-reminder: hay: **Land**
(06:13:07) birthday-reminder: Birthday not found. :~(

---

(06:13:50) birthday-reminder: Scanning mecha...
(06:13:50) birthday-reminder: needle: **Birthday**
(06:13:50) birthday-reminder: hay: **Vorname**
(06:13:50) birthday-reminder: hay: **Geburtstag**
(06:13:50) birthday-reminder: hay: **Geschlecht**
(06:13:50) birthday-reminder: hay: **Language**
(06:13:50) birthday-reminder: hay: **Land**
(06:13:50) birthday-reminder: hay: **Province**
(06:13:50) birthday-reminder: hay: **Stadt**
(06:13:50) birthday-reminder: hay: **Info**
(06:13:50) birthday-reminder: Birthday not found. :~(

---

The first two are from german and the other two from american users.

**Comment by kgraefe** [comment]
Can you do this for a working skypeweb account, too?

What is the skypeweb version you are using?

**Comment by TomTheDragon** [comment]
Sure i can and.. it did not work with the ones it did work before, looks like they changed something on the plugin or so :/
I am using the 1.1 release. (07.01.16)

**Comment by kgraefe** [comment]
Okay, apparently the skypeweb does not ship its own translation and I wonder, how it could work for some of your contacts in the first place, hm. I could not find out for certain, but I'd guess the plugin is just using the translations shipped with Pidgin.

Please try [this commit](https://github.com/kgraefe/pidgin-birthday-reminder/commit/91f7b0cd59b1dc88a30071c9e0488e4841f1f8b9) ([Win32](https://github.com/kgraefe/pidgin-birthday-reminder/raw/gh-pages/downloads/pidgin-birthday-reminder-1.8-debug-git91f7b0c-win32.zip)). It basically matches against the strings "Birthday" and its translation that is shipped with Pidgin. That way the birthday reminder should not break even if skypeweb starts to ship its own translations (as long as they match Pidgin's translation for this particular string).

**Comment by TomTheDragon** [comment]
I tested it and my CPU did go up to 100% for over 15 minutes until i killed Pidgin.
But it did seem to work fine after a restart and he did get really every birthday date :)
But only if you show that info page on every of your buddies and it can be a little stressful if you have some hundreds of skype buddies in your list ;)

**Comment by kgraefe** [comment]
That is because:
- The plugin waits two minutes between two automatic scans because some protocols did not like it, when it scanned all at once.
- Your buddies have already been scanned and will not be scanned again automatically. Due to this bug they did not have a birthday attached, though.

Thank you very much for your help.

**Comment by TomTheDragon** [comment]
Hm its just an idea but.. how about different waiting times for different protocols then? I know that ICQ for example is really picky about its limits but skypeweb seems to have a really big limits for scanning of profile infos.

**Comment by kgraefe** [comment]
That requires a major rewrite of the scan algorithm. Currently the plugin cycles through all contacts globally. To implement this, one cycle loop per supported protocol would be needed.

**Comment by TomTheDragon** [comment]
Well.. it was just a idea to make the scanning a little bit quicker, since the standard method can take quite a while.
