### ISSUE TITLE
Cannot activate Birthday Reminder under Ubuntu

### ISSUE THREAD

**Issue by bubjo** [kgraefe/pidgin-birthday-reminder#6]
After I updated the birthday reminder from version 1.7 to 1.9, I cannot activate the plug-in. I use pidgin 2.10.11 under Ubuntu 15.10. Is this an error or is this my mistake.

![bildschirmfoto vom 2016-02-08 22-56-26](https://cloud.githubusercontent.com/assets/17131037/12900615/8d1cbff6-ceb7-11e5-9067-e95d7f786151.png)

**Comment by kgraefe** [comment]
Just to clarify: You clicked the small box on the left and the hook did not appear?

Please open the debug window (Buddy List &rarr; Help &rarr; Debug window) before ticking the small box and see if it tells you (or me) something useful.

**Comment by kgraefe** [comment]
Okay, now I see that the plugin is not translated either. Probably, the plugin does not load because it does not find its icons. Something went wrong during your installation.

Can you please describe your installation process in detail?

**Comment by bubjo** [comment]
That's right. In the debug window I get the error message birthday-reminder: Could not load icons!

I attached you the log of the installation.

[install.txt](https://github.com/kgraefe/pidgin-birthday-reminder/files/122354/install.txt)

**Comment by bubjo** [comment]
I found an old package pidgin-birthday-reminder-dev. After I removed this package and reinstall pidgin-birthday-reminder version 1.9, it was in German and I works.

Thank you for your support.
