### ISSUE TITLE
Plural in German translation fails: "wird morgen 42 years alt"

### ISSUE THREAD

**Issue by kgraefe** [kgraefe/pidgin-birthday-reminder#7]
![bild_2017-11-08_17-55-24](https://user-images.githubusercontent.com/3797324/32563163-c914a884-c4b0-11e7-8b39-f6b2ed25a96b.png)

**Comment by kgraefe** [comment]
Should be: "Fischel wird morgen 42 Jahre alt!"

**Comment by Siggi0904** [comment]
In addition the age of a buddy is not translated too.
![bild_2017-11-08_18-17-38](https://user-images.githubusercontent.com/4992106/32563528-cecbe78c-c4b1-11e7-97a3-6dea2b7af727.png)

**Comment by kgraefe** [comment]
Should be fixed. I attached a Win32 binary of the current development version: [pidgin-birthday-reminder-1.11-3-g3c135ee-win32.zip](https://github.com/kgraefe/pidgin-birthday-reminder/files/1524347/pidgin-birthday-reminder-1.11-3-g3c135ee-win32.zip)

**Comment by Siggi0904** [comment]
I'll try and give a short feedback. Thanks.
